CREATE TABLE `message_monitor` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `biz_no` varchar(64) NOT NULL DEFAULT '' COMMENT '业务标识',
  `topic` varchar(255) NOT NULL DEFAULT '' COMMENT '消息主题',
  `tag` varchar(255) DEFAULT NULL COMMENT '消息标签',
  `content` varchar(10240) DEFAULT NULL COMMENT '消息文本',
  `msg_id` varchar(128) DEFAULT NULL COMMENT '消息ID',
  `next_send_time` datetime NOT NULL COMMENT '下次发送时间',
  `status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '发送状态:0-待发送,1-成功,2-失败,3-待回执,4-取消',
  `need_receipt` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否需要回执:0-否,1-是',
  `try_times` int(11) NOT NULL DEFAULT '0' COMMENT '尝试次数',
  `max_try_times` int(11) NOT NULL DEFAULT '-1' COMMENT '最大尝试次数(-1表示无限)',
  `retry_interval` int(11) NOT NULL DEFAULT '10' COMMENT '重试间隔秒数',
  `publish_listener` varchar(128) DEFAULT NULL COMMENT '发送结果监听器',
  `send_time` datetime DEFAULT NULL COMMENT '发送时间',
  `receipt_time` datetime DEFAULT NULL COMMENT '回执时间',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_biz_no` (`biz_no`),
  KEY `idx_msg_id` (`msg_id`),
  KEY `idx_topic` (`topic`),
  KEY `idx_next_time` (`next_send_time`),
  KEY `idx_send_time` (`send_time`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='消息监控';
